server:
  port: 8888

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/meter?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl